name: Exposer l'application Flask avec Ngrok

on:
  push:
    branches:
      - main

jobs:
  expose_flask_app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer les dépendances Python
      run: |
        python -m pip install --upgrade pip
        pip install Flask==2.0.2
        pip install flask-mysql==1.5.2
        pip install flask-cors==4.0.0


    - name: Démarrer l'application Flask
      run: |
        export FLASK_APP=app.py  # Remplacez app.py par le nom de votre fichier Flask
        flask run --host=127.0.0.1 --port=5000 &  # Lance l'application Flask en arrière-plan

    - name: Télécharger et installer Ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip

    - name: Authentifier votre compte Ngrok
      run: |
        ./ngrok authtoken 2YdteexLJfFhsyr9Mw0vLTHyrEx_4Fm4PsUKTaRwc1eGdh5d  # Remplacez VOTRE_JETON_NGROK par votre jeton Ngrok

    - name: Exposer l'application via Ngrok avec votre compte
      run: |
        ./ngrok http 5000  # Remplacez 5000 par le port sur lequel votre application Flask est en cours d'exécution

    # Ajoutez des étapes supplémentaires pour gérer le reste du workflow, comme les tests, etc.
