name: Deploy Flask API

on:
  push:
    branches:
      - main  # Déclencher le workflow lors des pushs sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Spécifier la version de Python à utiliser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask app
        run: |
          export FLASK_APP=app.py  # Remplacer 'your_app.py' par le nom de votre fichier Flask
          flask run --host=0.0.0.0
